### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by don-vip** [DearRude/IranianJOSMValidation#1]
https://github.com/DearRude/IranianPresets/raw/gh-pages/IranianPersets.zip is dead
I removed it from https://josm.openstreetmap.de/wiki/PresetsSource

**Comment by DearRude** [comment]
Nothing has changed in the repo recently and it's working right now. I guess it was a github-side problem. 
Can you check it again now?

**Comment by don-vip** [comment]
Ah it's working now! I've readded the link, thank you!
